name: Java CI with Maven

on:
  push:
    branches: [ maven ]
  pull_request:
    branches: [ maven ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
      - name: Check if slot exists
        run: |
          if az webapp deployment slot show --name <despliegueloreyjuan> --resource-group <GestionConfiguracion> --slot <slot>; then
            echo "El slot existe."
          else
            echo "El slot no existe."
            exit 1
          fi
      - name: Build with Maven Wrapper
        run: ./mvnw -B package
        continue-on-error: false
      - name: Send notification on error
        if: ${{ failure() }}
        run: |
          echo "Se produjo un error en la canalización."
          # Agrega aquí el código para enviar una alerta por correo electrónico o mensaje de texto.
